---
ID: "d97e4127-4554-41c1-a613-367ecc50ee56"
Parent: "b5e9debd-e2a8-48b9-a861-b1211f0fbddf"
Template: "b5e9debd-e2a8-48b9-a861-b1211f0fbddf"
Path: /sitecore/templates/Project/Hackathon/Content Types/Judge/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T192849Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "fec9f9ac-c102-4589-8b7d-8597cdb391d3"
      Hint: Full Name
      Value: $name
