---
ID: "2a1f226f-9967-408d-8da7-cdf00b8bdc67"
Parent: "13bf2a3b-f41c-47af-94c9-4610aa036b19"
Template: "13bf2a3b-f41c-47af-94c9-4610aa036b19"
Path: /sitecore/templates/Project/Hackathon/Page/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {13BF2A3B-F41C-47AF-94C9-4610AA036B19}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{BCFC7537-EFF4-434C-96F5-BF4F55FD175B}" />
      <d
        id="{0B4A31C9-712D-4578-A396-2DDC0F34B63A}"
        l="{72C595AD-68BB-44BC-B5CD-2A857039515F}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0cd046d4-09cf-4403-a05c-a8ba1fd09e74"
      Hint: Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T021108Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
