---
ID: "2e8efd05-b372-46be-a6aa-d8dfe0bb9a24"
Parent: "7d7c51eb-0207-4f09-bf6d-87724a51d1df"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Hackathon/Hackathon/Hackathon Registration Form/Page/Container/Section1/TeamCountrySection/Country/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T082245Z
