---
ID: "7c54358d-ca61-4078-8464-f1d4b575d1e8"
Parent: "c5594bb0-278a-432a-9ccb-b674bf3919e3"
Template: "c5594bb0-278a-432a-9ccb-b674bf3919e3"
Path: /sitecore/templates/Project/Hackathon/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T021108Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
